### ISSUE TITLE
how to run??

### ISSUE THREAD

**Issue by jiangxiongxiong** [CodeArtemis/TriggerRally#57]
OK,now I have "sh server/build/build.sh" in command line,but I do not know how to run this programme? I try to "minit serve" like this,but there is no file "index.html",ask for help! thanks..

**Comment by jareiko** [comment]
Hello! You will need to install CoffeeScript and start the server with something like this:

```
$ npm install -g coffee-script
$ coffee server/app.coffee
```

**Comment by jiangxiongxiong** [comment]
My operating system is ubuntu 11.04, I use "npm install -g coffee-script",but there are some errors:
/********_/
npm ERR! System Linux 2.6.38-16-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "coffee-script"
npm ERR! cwd /home/jxd/下载/TriggerRally-3
npm ERR! node -v v0.10.8
npm ERR! npm -v 1.2.23
npm ERR! path /home/jxd/tmp/npm-2697
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/jxd/tmp/npm-2697'
npm ERR! 
npm ERR! Additional logging details can be found in:
/**_***/

so I use "apt-get install coffeescript", but there are some new errors when I use "coffee server/app.coffee" 
/*****/
module.js:398
    throw new Error('require.registerExtension() removed. Use '......

**Comment by jiangxiongxiong** [comment]
Now  I use "sudo npm install -g coffee-script",then "coffee server/app.coffee",new errors:

/*******/
Error: Cannot find module './config'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)

**Comment by jareiko** [comment]
Oops, missed this, sorry. See issue #6.

**Comment by winstonhong** [comment]
Hello folks.

As TriggerRally has made some new commits over the last few months, I can NOT run TriggerRally game server using the latest version at GitHub. 

There is no any stable releases for TriggerRally, therefore, I can NOT try any old version.

I describe my installation procedure as follows.

---

(1) I download the latest version of TriggerRally from GitHub.
https://github.com/CodeArtemis/TriggerRally

I install node.js, coffee, and node_modules in the latest version using apt-get install, npm install
node v0.10.26, express@4.1.0, CoffeeScript version 1.7.1
ubuntu 12.04
under server folder, I use npm install the necessary node_modules required by package.json

Run  server/build/build.sh  to build production-mode JS bundles successfully.

Following the instruction in the issue #6, I create the config file './config' 

(2) I found that TriggerRally game at GitHub can NOT work on express 4.x

"Because in Express 4.0, all middleware (except static) have been removed and will need to be called separately. These middleware dependencies were included in the Connect package. Since connect is no longer a dependency, we will have to call the middleware ourselves. Here is a table of all the middleware that came with 3.0 and what it is now called."

http://scotch.io/bar-talk/expressjs-4-0-new-features-and-upgrading-from-3-0

With reference to the above link, I have modified the source code to make the source code adapt to express@4.1.0.

(3) When I start the game server (coffee server/app.coffee) , it exhibits the 

Error: Cannot find module './secret'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/winston/TriggerRally-unified/server/paypal/expresscheckout.coffee:2:15)
  at Object.<anonymous> (/home/winston/TriggerRally-unified/server/paypal/expresscheckout.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/winston/TriggerRally-unified/server/app.coffee:292:8)
  at Object.<anonymous> (/home/winston/TriggerRally-unified/server/app.coffee:1:1)
  at Module._compile (module.js:456:26)

I check Paypal app's developer link, I do NOT know how to figure out the "server/paypal/secret.coffee" format of TriggerRally.  

https://developer.paypal.com/docs/integration/admin/manage-apps/

(4) I comment out the source code related to Paypal communication. Then I run the game server again (coffee server/app.coffee).

info  - socket.io started
[2014-04-28T03:18:37.269Z] Server listening on port 80 in development mode
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [192.168.0.102:27017]
  at [object Object].<anonymous> (/home/winston/TriggerRally-unified/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
  at [object Object].EventEmitter.emit (events.js:106:17)
  at [object Object].<anonymous> (/home/winston/TriggerRally-unified/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at Socket.<anonymous> (/home/winston/TriggerRally-unified/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
  at Socket.EventEmitter.emit (events.js:95:17)
  at net.js:440:14
  at process._tickCallback (node.js:415:13)

---

Would you please give some clues so that I can run game in my local ubuntu server? Thank you very much.
