### ISSUE TITLE
Can not build 

### ISSUE THREAD

**Issue by newcou** [CodeArtemis/TriggerRally#60]
sh server/build/build.sh 

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/liuweijia/game/server/node_modules/requirejs/bin/r.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

coffee server/app.coffee 
Error: Cannot find module 'underscore'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/liuweijia/game/server/app.coffee:3:21, <js>:6:7)
  at Object.<anonymous> (/home/liuweijia/game/server/app.coffee:1:1, <js>:827:4)
  at Module._compile (module.js:456:26)

**Comment by newcou** [comment]
i did not install the coffee-script.
sudo npm install -g coffee-script
sudo npm -g install requirejs
sudo npm -g install uglifyjs
cp -r /usr/lib/node_modules/ server/ 
sh server/build/build.sh 
at the end of the results:
server/build/build.sh: 16: server/build/build.sh: uglifyjs: not found

so
sudo npm -g install uglify-js

fun again,at last for the results,i gave it up!

Tracing dependencies for: ../js/almond

Tracing dependencies for: coffee-script

## /home/liuweijia/game/server/public/build-out/main.js

/home/liuweijia/game/server/public/scripts/../js/almond.js
/home/liuweijia/game/server/public/js/cs.js
/home/liuweijia/game/server/public/js/jquery-2.0.0.min.js
/home/liuweijia/game/server/public/js/underscore-min.js
/home/liuweijia/game/server/public/js/backbone-min.js
cs!models/index
cs!views/view
/home/liuweijia/game/server/public/js/require-jade.js
jade!templates/about
cs!views/about
/home/liuweijia/game/server/public/js/three-r54.js
/home/liuweijia/game/server/public/scripts/util/util.js
/home/liuweijia/game/server/public/scripts/client/car.js
/home/liuweijia/game/server/public/scripts/util/LFIB4.js
cs!util/collision
cs!util/hash2d
/home/liuweijia/game/server/public/scripts/game/scenery.js
/home/liuweijia/game/server/public/js/async.min.js
/home/liuweijia/game/server/public/scripts/util/image.js
cs!util/quiver
/home/liuweijia/game/server/public/scripts/game/terrain.js
/home/liuweijia/game/server/public/scripts/game/track.js
/home/liuweijia/game/server/public/scripts/util/pubsub.js
/home/liuweijia/game/server/public/scripts/game/sim.js
/home/liuweijia/game/server/public/scripts/game/vehicle.js
/home/liuweijia/game/server/public/scripts/util/browserhttp.js
/home/liuweijia/game/server/public/scripts/game/game.js
jade!templates/drive
cs!util/recorder
cs!views/drive
cs!util/util2
cs!client/misc
cs!client/editor_camera
cs!editor/ops
cs!views/view_collection
jade!templates/tracklistentry
cs!views/tracklist
jade!templates/user
jade!templates/userstatus
cs!views/user
cs!views/inspector
jade!templates/editor
cs!views/editor
jade!templates/home
cs!views/home
jade!templates/ignition
cs!util/popup
cs!views/ignition
jade!templates/license
cs!views/license
jade!templates/mayhem
cs!views/mayhem
jade!templates/packa
cs!views/packa
jade!templates/profile
cs!views/profile
cs!views/replay
cs!views/spin
jade!templates/favorite
cs!views/favorite
jade!templates/track
jade!templates/trackrun
cs!views/track
jade!templates/trackset
jade!templates/tracksetentry
cs!views/trackset
cs!router
jade!templates/notfound
cs!views/notfound
jade!templates/purchase
cs!views/purchase
jade!templates/credits
cs!views/credits
jade!templates/statusbar
jade!templates/statusbarcar
jade!templates/music
cs!views/music
cs!views/statusbar
/home/liuweijia/game/server/public/scripts/client/audio.js
cs!client/array_geometry
cs!client/scenery
cs!client/terrain
cs!game/synchro
cs!client/client
jade!templates/unified
cs!views/unified
cs!app
/home/liuweijia/game/server/public/scripts/main.js

WARN: Dropping unused variable interp [../public/build-out/main.js:45744,4]
WARN: Dropping unused function argument popup [../public/build-out/main.js:45769,324]
WARN: Dropping unused variable interp [../public/build-out/main.js:45980,4]
WARN: Dropping unused variable interp [../public/build-out/main.js:45993,4]
WARN: Dropping unused variable interp [../public/build-out/main.js:46421,4]
WARN: Dropping unused function argument event [../public/build-out/main.js:46559,54]
WARN: Dropping unused variable interp [../public/build-out/main.js:46603,4]
WARN: Dropping unused function argument event [../public/build-out/main.js:46669,41]
WARN: Dropping unused variable interp [../public/build-out/main.js:46744,4]
WARN: Dropping unused function argument event [../public/build-out/main.js:47006,68]
WARN: Dropping unused function argument event [../public/build-out/main.js:47021,68]
WARN: Dropping unused function argument models [../public/build-out/main.js:46910,283]
WARN: Dropping unused function argument quiver [../public/build-out/main.js:47553,118]
WARN: Dropping unused function argument delta [../public/build-out/main.js:48331,66]
WARN: Dropping unused function argument camera [../public/build-out/main.js:48331,58]

....................................

Somebody help
