### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Rocks360** [CodeArtemis/TriggerRally#75]
Hello all, 

I run the build.sh file after I installed requirejs. It works fine but now when I try to start the node server with the following command "node server/public/build-v3/main.js" I get this error output: 

/Users/someuser/NodeJs_Projects/TriggerRally/server/public/build-v3/main.js:3
n||0===n)if("object"===oe.type(n))oe.merge(f,n.nodeType?[n]:n);else if(De.test(n)){for(o=o||p.appendChild(t.createElement("div")),a=(Pe.exec(n)||["",""])[1].toLowerCase(),s=Oe[a]||Oe._default,o.innerHTML=s[1]+n.replace(ke,"<$1></$2>")+s[2],c=s[0];c--;)o=o.firstChild;oe.merge(f,o.childNodes),o=p.firstChild,o.textContent=""}else f.push(t.createTextNode(n));for(p.textContent="",u=0;n=f[u++];)if((!i||-1===oe.inArray(n,i))&&(l=oe.contains(n.ownerDocument,n),o=g(p.appendChild(n),"script"),l&&d(o),r))for(c=0;n=o[c++];)Ne.test(n.type||"")&&r.push(n);return p},cleanData:function(e){for(var t,r,i,n=e.length,o=0,a=oe.event.special;n>o;o++){if(r=e[o],oe.acceptData(r)&&(t=ge.access(r)))for(i in t.events)a[i]?oe.event.remove(r,i):oe.removeEvent(r,i,t.handle);me.discard(r),ge.discard(r)}},_evalUrl:function(e){return oe.ajax({url:e,type:"GET",dataType:"text",async:!1,global:!1,success:oe.globalEval})}}),oe.fn.extend({wrapAll:function(e){var t;

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/someuser/NodeJs_Projects/TriggerRally/server/public/build-v3/main.js:3:21254)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Its my problem too
